"""Build quiz HTML from 200 questions with correct answer key."""
import json

# Each question: (text, [4 options A,B,C,D], correct_index 0-3)
# Indexes 0..49 = Part 1, 50..99 = Part 2, 100..149 = Part 3, 150..199 = Part 4

QUESTIONS = [
    # ========== PART 1 (Q1-50) ==========
    ("Đối tượng chủ yếu của tâm lí học trẻ em là:",
     ["Đời sống tâm lí của trẻ trong quá trình phát triển", "Cơ thể sinh lí của trẻ em", "Hành vi người lớn đối với trẻ", "Các bệnh lí tâm thần ở người trưởng thành"], 0),
    ("Mục đích cơ bản của việc nghiên cứu tâm lí trẻ em là:",
     ["Mô tả đơn thuần các hiện tượng tâm lí", "Hiểu để giáo dục, nuôi dạy trẻ tốt hơn", "Giúp trẻ rèn luyện thể thao", "Tăng cường trí nhớ cho người lớn"], 1),
    ("“Đời sống tâm lí của trẻ thay đổi cùng với hoạt động và giao tiếp” thể hiện:",
     ["Đối tượng của tâm lí học", "Nhiệm vụ của tâm lí học", "Một quy luật phát triển tâm lí", "Ý nghĩa của công tác giáo dục"], 2),
    ("Nhiệm vụ quan trọng của tâm lí học trẻ em không phải là:",
     ["Khám phá quy luật phát triển tâm lí trẻ", "Giải thích cơ chế hình thành các phẩm chất nhân cách", "Đề xuất biện pháp giáo dục phù hợp", "Kê đơn điều trị bệnh cơ thể cho trẻ"], 3),
    ("Khi nói “giúp giáo viên hiểu trẻ để lựa chọn phương pháp dạy học”, ta nhấn mạnh:",
     ["Ý nghĩa thực tiễn của tâm lí học trẻ em", "Đối tượng của tâm lí học trẻ em", "Phương pháp nghiên cứu", "Lịch sử hình thành môn học"], 0),
    ("Tâm lí học trẻ em khác với tâm lí học người lớn chủ yếu ở:",
     ["Đối tượng nghiên cứu là con người", "Sử dụng một số phương pháp quan sát", "Nghiên cứu sự phát triển tâm lí gắn với từng lứa tuổi", "Sử dụng khái niệm nhân cách"], 2),
    ("Trong cấu trúc khoa học, tâm lí học trẻ em thuộc nhóm:",
     ["Tâm lí học phát triển", "Tâm lí học xã hội", "Tâm lí học lao động", "Tâm lí học lâm sàng"], 0),
    ("Tâm lí học trẻ em có quan hệ chặt chẽ nhất với:",
     ["Giáo dục học mầm non", "Toán học", "Sinh thái học", "Kinh tế học"], 0),
    ("Khi nghiên cứu “đặc điểm tiếp thu của trẻ 4-5 tuổi trong trò chơi”, nhà tâm lí học thuộc lĩnh vực:",
     ["Tâm lí học xã hội", "Tâm lí học trẻ em", "Tâm lí học lao động", "Tâm lí học y học"], 1),
    ("Ý nghĩa của tâm lí học trẻ em đối với giáo viên mầm non không phải là:",
     ["Hiểu đặc điểm tâm lí trẻ để lựa chọn nội dung giáo dục", "Dự đoán những khó khăn trẻ có thể gặp", "Tự rèn luyện nhân cách người giáo viên", "Chẩn đoán bệnh lí nội khoa cho trẻ"], 3),
    ("Nội dung “giúp cha mẹ hiểu quy luật phát triển của con” thể hiện:",
     ["Đối tượng", "Nhiệm vụ", "Phương pháp", "Lịch sử của ngành"], 1),
    ("Một trong các nhiệm vụ của tâm lí học trẻ em là:",
     ["Nghiên cứu cấu tạo não bộ chi tiết của trẻ", "Phát hiện nguyên nhân tâm lí của khó khăn học tập", "Xây dựng chương trình giáo dục quốc gia", "Quản lí nhà trường mầm non"], 1),
    ("Khẳng định nào sau đây đúng với khái niệm phát triển tâm lí:",
     ["Sự tăng đơn thuần về số lượng hành vi", "Sự thay đổi mang tính lặp lại y nguyên", "Sự biến đổi cả về chất và lượng trong đời sống tâm lí", "Sự già đi về mặt sinh lí của cơ thể"], 2),
    ("Phát triển tâm lí trẻ em diễn ra:",
     ["Tự phát, không phụ thuộc điều kiện sống", "Chỉ do di truyền quyết định", "Trong mối quan hệ với môi trường và giáo dục", "Chỉ do hoạt động vui chơi quyết định"], 2),
    ("Quy luật “phát triển không đồng đều” thể hiện ở chỗ:",
     ["Các mặt tâm lí tăng trưởng hoàn toàn như nhau", "Ở mỗi giai đoạn, có những chức năng phát triển mạnh hơn", "Tâm lí trẻ luôn phát triển tuyến tính, thẳng tắp", "Mặt trí tuệ luôn đi sau mặt tình cảm"], 1),
    ("Khi nói “phát triển tâm lí có tính toàn vẹn”, ý đúng nhất là:",
     ["Chỉ trí tuệ phát triển, các mặt khác không đổi", "Các mặt tâm lí liên quan chặt chẽ, tác động lẫn nhau", "Từng chức năng phát triển tách biệt", "Sự phát triển tâm lí không liên quan cơ thể"], 1),
    ("Đặc điểm nào thuộc bản chất phát triển tâm lí trẻ em:",
     ["Vừa mang tính kế thừa, vừa mang tính sáng tạo", "Chỉ do giáo dục quyết định", "Không phụ thuộc hoạt động", "Không cần giao tiếp xã hội"], 0),
    ("Khái niệm “lứa tuổi” trong tâm lí học trẻ em được hiểu là:",
     ["Khoảng thời gian trẻ sống trên Trái Đất", "Tập hợp những trẻ có cùng năm sinh", "Giai đoạn phát triển có cấu trúc hoạt động, quan hệ xã hội và đặc điểm tâm lí tương đối ổn định", "Mốc tuổi ghi trên giấy khai sinh"], 2),
    ("Khi nói “khủng hoảng 3 tuổi” là nhấn mạnh:",
     ["Trẻ thường mắc nhiều bệnh", "Trẻ có bước ngoặt quan hệ với người lớn, khẳng định cái tôi", "Trẻ phát triển thể lực rất nhanh", "Trẻ bắt đầu đến nhà trẻ"], 1),
    ("Sự phát triển tâm lí trẻ em không chịu ảnh hưởng trực tiếp của:",
     ["Di truyền", "Hoạt động và giao tiếp", "Giáo dục có mục đích", "Tình hình thời tiết từng ngày"], 3),
    ("Hình thức hoạt động chủ đạo ở trẻ lứa tuổi mầm non là:",
     ["Lao động sản xuất", "Chơi", "Học tập nghề nghiệp", "Hoạt động nghiên cứu khoa học"], 1),
    ("Hoạt động chủ đạo có ý nghĩa vì:",
     ["Chiếm nhiều thời gian nhất trong ngày", "Là hoạt động đem lại lương cao", "Quy định những biến đổi chủ yếu trong tâm lí của lứa tuổi", "Là hoạt động theo yêu cầu người lớn"], 2),
    ("Giao tiếp của trẻ mầm non với người lớn chủ yếu thông qua:",
     ["Công việc lao động nặng nhọc", "Ngôn ngữ và các hành động trực tiếp", "Thư điện tử và mạng xã hội", "Văn bản hành chính"], 1),
    ("Vai trò của giao tiếp đối với phát triển tâm lí trẻ là:",
     ["Ít quan trọng vì trẻ chủ yếu học từ đồ chơi", "Chỉ giúp trẻ giải trí", "Tạo điều kiện hình thành ý thức, nhân cách, lĩnh hội kinh nghiệm xã hội", "Chỉ rèn luyện ngôn ngữ"], 2),
    ("Biểu hiện nhân cách trẻ mầm non không bao gồm:",
     ["Thái độ với người xung quanh", "Hệ thống tri thức, kĩ năng", "Hình dáng cơ thể trẻ", "Các chuẩn mực hành vi trẻ tiếp thu"], 2),
    ("Phương pháp nghiên cứu cơ bản trong tâm lí học trẻ em là:",
     ["Phương pháp quan sát", "Phương pháp giải phẫu", "Phương pháp thử nghiệm hoá học", "Phương pháp thống kê dân số"], 0),
    ("Trong nghiên cứu trẻ mầm non, phương pháp quan sát yêu cầu trước hết:",
     ["Quan sát thật lâu, không cần kế hoạch", "Chỉ nhìn khi trẻ đang ngủ", "Quan sát theo cảm hứng cá nhân", "Có mục đích, kế hoạch, biết ghi chép kết quả"], 3),
    ("Ưu điểm lớn nhất của phương pháp quan sát là:",
     ["Tiết kiệm thời gian hơn mọi phương pháp", "Không cần chuẩn bị gì", "Cho phép ghi nhận hành vi tự nhiên của trẻ trong hoàn cảnh sống thực", "Dễ suy luận nguyên nhân một cách chính xác tuyệt đối"], 2),
    ("Hạn chế chủ yếu của quan sát là:",
     ["Không thể áp dụng ở lứa tuổi nhỏ", "Kết quả phụ thuộc nhiều vào chủ quan người quan sát", "Không thể ghi âm, ghi hình", "Không dùng được trong trường mầm non"], 1),
    ("“Tác động một cách có chủ định vào điều kiện để xem sự thay đổi tâm lí” là nội dung của:",
     ["Quan sát", "Phỏng vấn", "Thực nghiệm tâm lí", "Điều tra bằng bảng hỏi"], 2),
    ("Thực nghiệm tự nhiên khác thực nghiệm trong phòng thí nghiệm ở chỗ:",
     ["Không có giả thuyết khoa học", "Tiến hành trong điều kiện sinh hoạt bình thường của trẻ", "Không có sự kiểm soát biến độc lập", "Không cần ghi chép kết quả"], 1),
    ("Trong nghiên cứu tâm lí trẻ, thực nghiệm trong phòng thí nghiệm thích hợp khi:",
     ["Muốn kiểm soát chặt chẽ các điều kiện ảnh hưởng", "Cần tác động vào trẻ trong nhiều tháng", "Chỉ muốn xem trẻ chơi tự do", "Không xác định được biến độc lập"], 0),
    ("“Bài tập phân loại tranh theo màu sắc để đo mức độ chú ý” là ví dụ của:",
     ["Quan sát", "Phỏng vấn", "Trắc nghiệm tâm lí", "Phương pháp tiểu sử"], 2),
    ("Trắc nghiệm tâm lí ở trẻ mầm non thường được sử dụng để:",
     ["Khám sức khỏe định kì", "Đo lường mức độ phát triển một số chức năng tâm lí", "Kiểm tra chiều cao cân nặng", "Đánh giá tài chính gia đình"], 1),
    ("Khi sử dụng trắc nghiệm, yêu cầu cơ bản là:",
     ["Cho trẻ tự làm theo ý muốn", "Thay đổi lời dẫn tuỳ cảm hứng", "Tuân thủ đúng hướng dẫn chuẩn, cách chấm điểm thống nhất", "Không cần quan tâm đến thời gian"], 2),
    ("“Phân tích sản phẩm hoạt động của trẻ” là phương pháp dựa trên:",
     ["Các sản phẩm do trẻ tạo ra (vẽ, nặn, xây dựng…)", "Lời kể của người lớn", "Ghi chép của giáo viên", "Sổ liên lạc gia đình"], 0),
    ("Ưu điểm của phương pháp phân tích sản phẩm hoạt động là:",
     ["Đo được mọi mặt tâm lí", "Không cần so sánh với chuẩn tuổi", "Không cần hiểu hoàn cảnh trẻ", "Thể hiện kết quả hoạt động mang tính ổn định, có thể xem lại nhiều lần"], 3),
    ("Hạn chế của phân tích sản phẩm hoạt động:",
     ["Không dùng được cho trẻ 5 tuổi", "Không quan tâm đến đặc điểm cá nhân", "Khó biết hết quá trình tâm lí diễn ra khi trẻ làm", "Không thể lưu trữ sản phẩm"], 2),
    ("Phương pháp đàm thoại (phỏng vấn) với trẻ mầm non cần chú ý:",
     ["Tạo bầu không khí gần gũi, dùng câu hỏi ngắn gọn, dễ hiểu", "Đặt nhiều câu hỏi trừu tượng", "Không cho trẻ hỏi lại", "Ghi âm là không cần thiết"], 0),
    ("Điều tra bằng bảng hỏi thường được sử dụng chủ yếu với:",
     ["Trẻ 3 tuổi", "Người bán hàng", "Giáo viên, cha mẹ", "Bác sĩ"], 2),
    ("Phương pháp tiểu sử trong tâm lí học trẻ em là:",
     ["Tổng hợp các hồ sơ sức khỏe", "Mô tả đời sống tâm lí dựa trên tư liệu về cả quá trình phát triển của một cá nhân", "Ghi lại kết quả học tập", "Lập sơ đồ quan hệ gia đình"], 1),
    ("Ý nghĩa của phương pháp tiểu sử là:",
     ["Nắm được quá trình hình thành những nét nhân cách riêng biệt", "Đo lường chính xác trí tuệ", "Đánh giá sức mạnh cơ bắp", "Xác định chỉ số thông minh tập thể"], 0),
    ("Khi nghiên cứu lịch sử phát triển tâm lí học trẻ em, người ta nhận thấy:",
     ["Môn học đã tồn tại ngay từ thời cổ đại", "Ban đầu, trẻ em ít được chú ý như một đối tượng riêng", "Từ đầu thế kỉ XX mới có suy nghĩ về trẻ em", "Trẻ em luôn được xem là trung tâm trong mọi thời kì"], 1),
    ("Quan điểm coi trẻ em là “người lớn thu nhỏ” xuất hiện chủ yếu ở:",
     ["Thời cổ đại và trung cổ", "Thời cận đại", "Thế kỉ XX", "Thời hiện nay"], 0),
    ("Nhà giáo dục I.A. Comenius (Comenxki) có công lao lớn vì:",
     ["Phát minh trắc nghiệm trí tuệ", "Xây dựng thuyết phân tâm", "Nhấn mạnh việc dạy học phù hợp với lứa tuổi, coi trọng giáo dục trẻ nhỏ", "Sáng lập trường phái hành vi"], 2),
    ("J.J. Rousseau với tác phẩm “Êmin” đã khẳng định:",
     ["Trẻ em sinh ra đã xấu", "Trẻ em phải học như người lớn", "Chỉ cần rèn trí tuệ, không cần đạo đức", "Giáo dục cần tôn trọng bản tính tự nhiên của trẻ, phát triển hài hòa"], 3),
    ("Trong lịch sử, sự ra đời của các trắc nghiệm trí tuệ Binet - Simon gắn với nhu cầu:",
     ["Chẩn đoán bệnh cơ thể", "Xếp loại gia đình giàu nghèo", "Đánh giá sức khỏe thể chất", "Phân loại trẻ theo chỉ số thông minh để có biện pháp giáo dục thích hợp"], 3),
    ("Tâm lí học trẻ em trở thành một ngành khoa học độc lập rõ nét vào:",
     ["Thế kỉ XVIII", "Cuối thế kỉ XIX - đầu thế kỉ XX", "Thế kỉ XVII", "Nửa sau thế kỉ XXI"], 1),
    ("Trường phái phân tâm (S. Freud) khi giải thích sự phát triển nhân cách trẻ nhấn mạnh:",
     ["Vai trò của vô thức, xung năng bên trong", "Tầm quan trọng của hành vi quan sát được", "Cấu trúc xã hội", "Hệ thống thưởng - phạt bên ngoài"], 0),
    ("Hạn chế cơ bản của thuyết phân tâm trong giáo dục trẻ là:",
     ["Không chú ý đến nội tâm", "Không quan tâm cảm xúc trẻ", "Không đề cập đến gia đình", "Tuyệt đối hóa vai trò bản năng, ít coi trọng hoạt động và giáo dục có ý thức"], 3),

    # ========== PART 2 (Q1-50) ==========
    ("Trường phái hành vi coi đối tượng nghiên cứu chủ yếu là:",
     ["Quá trình tư duy", "Hành vi quan sát được và các phản ứng bên ngoài", "Cảm xúc chủ quan", "Giấc mơ của trẻ"], 1),
    ("Nguyên tắc giáo dục rút ra từ thuyết hành vi là:",
     ["Dựa vào vô thức", "Bỏ qua môi trường", "Tổ chức hệ thống thưởng - phạt để hình thành hành vi mong muốn", "Chỉ cần giải thích bằng lời"], 2),
    ("Hạn chế của thuyết hành vi trong việc hiểu trẻ em:",
     ["Không chú ý đến hành vi", "Không liên hệ thực tiễn", "Không dùng thực nghiệm", "Coi nhẹ quá trình bên trong, không thấy vai trò chủ thể tích cực của trẻ"], 3),
    ("Tâm lí học Gestalt nhấn mạnh:",
     ["Tính chỉnh thể, cấu trúc của tri giác và suy nghĩ", "Các yếu tố riêng lẻ tách rời", "Phản xạ có điều kiện", "Sức mạnh của vô thức"], 0),
    ("Quan điểm của L.X. Vưgôtxki coi sự phát triển tâm lí trẻ em:",
     ["Thuần sinh học", "Hoàn toàn do trí thông minh bẩm sinh", "Mang bản chất xã hội - lịch sử, diễn ra qua hoạt động và giao tiếp", "Không phụ thuộc vào văn hóa"], 2),
    ("Khái niệm “vùng phát triển gần nhất” dùng để chỉ:",
     ["Khoảng cách giữa chiều cao và cân nặng", "Khoảng cách giữa trẻ và người lớn", "Khoảng cách giữa trình độ hiện tại của trẻ và trình độ có thể đạt được nhờ giúp đỡ", "Khoảng cách giữa hai lứa tuổi"], 2),
    ("Theo L.X. Vưgôtxki, phương tiện tâm lí quan trọng nhất trong phát triển của trẻ là:",
     ["Cơ bắp", "Thính giác", "Thị lực", "Ngôn ngữ"], 3),
    ("A.N. Lêônchiep phát triển thuyết hoạt động cho rằng:",
     ["Hoạt động của trẻ chỉ là kết quả kích thích - phản ứng", "Hoạt động không liên quan đến tâm lí", "Hoạt động là đơn vị phân tích cơ bản của đời sống tâm lí", "Chỉ có trò chơi mới là hoạt động"], 2),
    ("Theo thuyết hoạt động, cấu trúc cơ bản gồm:",
     ["Hoạt động - hành động - thao tác", "Hành vi - phản ứng - kích thích", "Nhân tố - kết quả - điều kiện", "Cảm giác - tri giác - tưởng tượng"], 0),
    ("Khi giáo viên tổ chức trò chơi đóng vai theo chủ đề để phát triển nhân cách, ta vận dụng chủ yếu:",
     ["Thuyết hành vi", "Thuyết hoạt động", "Thuyết phân tâm", "Thuyết nhân chủng học"], 1),
    ("Theo thuyết nhân văn, mục tiêu cao nhất của phát triển con người là:",
     ["Thích nghi tối thiểu", "Tăng sức mạnh thể chất", "Tự hiện thực hóa bản thân", "Tích luỹ của cải"], 2),
    ("Trong giáo dục mầm non, quan điểm nhân văn gợi ý giáo viên cần:",
     ["Tôn trọng, lắng nghe, khuyến khích tiềm năng của từng trẻ", "Kiểm soát trẻ bằng mệnh lệnh", "Chỉ chú ý trẻ giỏi", "Dùng phạt là chính"], 0),
    ("Sự phát triển tâm lí trẻ em có tính lịch sử vì:",
     ["Gắn chặt với điều kiện xã hội - văn hóa cụ thể", "Trẻ em ở mọi thời đại giống hệt nhau", "Chỉ do gen quyết định", "Không liên quan hoàn cảnh"], 0),
    ("“Tính mềm dẻo” của hệ thần kinh và tâm lí trẻ thể hiện:",
     ["Dễ bị tổn thương, không thể thay đổi", "Không cần môi trường kích thích", "Không chịu ảnh hưởng của giáo viên", "Có khả năng tiếp thu, cải biến dưới tác động giáo dục"], 3),
    ("Yếu tố quyết định trực tiếp đến hướng phát triển nhân cách trẻ mầm non là:",
     ["Di truyền", "Sự may mắn", "Khí hậu", "Giáo dục, đặc biệt là giáo dục mầm non và gia đình"], 3),
    ("Trong nghiên cứu, việc kết hợp nhiều phương pháp nhằm:",
     ["Tăng khối lượng công việc", "Làm khó người nghiên cứu", "Kiểm chứng, bổ sung kết quả cho nhau, nâng cao độ tin cậy", "Giảm tính khách quan"], 2),
    ("Khi quan sát trẻ, việc ghi nhận các câu nói nguyên văn của trẻ giúp:",
     ["Làm rõ hơn quá trình suy nghĩ, cảm xúc", "Lãng phí thời gian", "Không cần thiết vì chỉ cần nhớ", "Chỉ mang ý nghĩa vui vẻ"], 0),
    ("Trong thực nghiệm với trẻ, yêu cầu đạo đức quan trọng là:",
     ["Có thể làm trẻ sợ để đo phản ứng", "Che giấu mục đích ngay cả với giáo viên", "Không cần hỏi ý kiến phụ huynh", "Không được gây tổn hại đến sức khỏe, tâm lí trẻ"], 3),
    ("Một đặc điểm của trẻ mầm non khiến việc sử dụng phỏng vấn phải điều chỉnh là:",
     ["Ngôn ngữ còn hạn chế, dễ bị gợi ý", "Trẻ chưa biết nói", "Trẻ hiểu hết mọi câu hỏi trừu tượng", "Trẻ không thích nói chuyện"], 0),
    ("Trong điều tra phụ huynh về biểu hiện tâm lí trẻ, câu hỏi nên:",
     ["Dài, phức tạp", "Đặt theo dạng đánh đố", "Mang tính chất kiểm tra kiến thức", "Ngắn, rõ ràng, tránh thuật ngữ chuyên môn"], 3),
    ("“Sản phẩm hoạt động của trẻ phản ánh trình độ phát triển tâm lí” vì:",
     ["Trong quá trình tạo sản phẩm, trẻ huy động tri giác, tưởng tượng, cảm xúc, kĩ năng", "Trẻ làm sản phẩm theo lệnh giáo viên", "Sản phẩm đẹp do giáo viên chỉnh", "Trẻ bắt chước mẫu có sẵn"], 0),
    ("Lịch sử phát triển tâm lí học trẻ em ở Nga/Xô viết gắn với các tên tuổi:",
     ["L.X. Vưgôtxki, A.N. Lêônchiep, Đ.B. Encônin…", "Pavlov, Mendel", "Skinner, Watson", "Rogers, Maslow"], 0),
    ("Quan điểm “giáo dục phải đi trước một bước” liên quan tới:",
     ["Thuyết hành vi", "Trường phái Gestalt", "Thuyết phân tâm", "Lý thuyết vùng phát triển gần nhất"], 3),
    ("Ý nghĩa của lịch sử tâm lí học trẻ em đối với sinh viên mầm non là:",
     ["Biết tên các nhà khoa học để thi", "Hiểu cơ sở hình thành quan điểm hiện đại, tránh tuyệt đối hóa một trường phái", "Không có ý nghĩa thực tiễn", "Chỉ dùng để làm bài tập lịch sử"], 1),
    ("Khi nói “trẻ em không phải là người lớn thu nhỏ”, điều này hàm ý:",
     ["Có thể dạy trẻ y như người lớn", "Trẻ có những quy luật phát triển riêng, cần phương pháp giáo dục đặc thù", "Trẻ nhỏ yếu hơn nên phải bảo vệ thụ động", "Trẻ không cần được tôn trọng"], 1),
    ("Một yếu tố làm phong phú đời sống tâm lí trẻ mầm non là:",
     ["Thiếu giao tiếp", "Môi trường hoạt động đa dạng, giàu kích thích", "Thiếu đồ chơi", "Bị cô lập"], 1),
    ("Nhận xét nào đúng về mối quan hệ giữa phát triển thể chất và phát triển tâm lí:",
     ["Hoàn toàn tách biệt", "Tâm lí phát triển độc lập", "Có quan hệ chặt chẽ, tác động qua lại", "Chỉ thể chất ảnh hưởng tâm lí"], 2),
    ("Để hiểu đúng hành vi của trẻ, giáo viên cần:",
     ["Tìm hiểu hoàn cảnh, động cơ, mối quan hệ", "Chỉ nhìn kết quả bên ngoài", "Dựa vào ấn tượng ban đầu", "Hỏi ý kiến bạn bè trẻ"], 0),
    ("Chính xác khi nói về nhân cách trẻ:",
     ["Chỉ gồm những đặc điểm bẩm sinh", "Không liên quan môi trường", "Không thay đổi sau 3 tuổi", "Hình thành dần trong hoạt động và giao tiếp, dưới ảnh hưởng giáo dục"], 3),
    ("Khi giáo viên sử dụng trò chơi như một “thực nghiệm tự nhiên”, cô đang:",
     ["Gây áp lực cho trẻ", "Tạo tình huống có chủ định để xem sự biến đổi tâm lí trong hoàn cảnh quen thuộc", "Làm trẻ quên nhiệm vụ học tập", "Không thể đo được gì"], 1),
    ("Phát triển tâm lí trẻ mang tính cá biệt vì mỗi trẻ:",
     ["Có tốc độ, con đường phát triển riêng", "Phát triển y hệt nhau", "Chỉ phụ thuộc gen", "Không chịu ảnh hưởng giáo dục"], 0),
    ("Khi đánh giá trẻ, cần tránh:",
     ["So sánh với chuẩn lứa tuổi", "Đánh giá dài hạn, toàn diện", "Gắn nhãn vội vàng dựa trên một hành vi đơn lẻ", "Kết hợp ý kiến gia đình"], 2),
    ("Giai đoạn 0-3 tuổi, hoạt động chủ đạo là:",
     ["Học tập có hệ thống", "Giao tiếp cảm xúc trực tiếp với người lớn", "Lao động", "Nghiên cứu khoa học"], 1),
    ("Trẻ mẫu giáo 3-6 tuổi, hoạt động chủ đạo:",
     ["Chơi đóng vai theo chủ đề", "Học nghề", "Lao động nặng", "Ngủ"], 0),
    ("Đặc điểm nổi bật của chơi đóng vai theo chủ đề là:",
     ["Thiên về vận động đơn thuần", "Trẻ thực hiện vai người lớn trong quan hệ xã hội tưởng tượng", "Không có luật", "Không có ý nghĩa giáo dục"], 1),
    ("Nhận xét đúng về xúc cảm trẻ mầm non:",
     ["Đơn giản, bộc lộ trực tiếp, dễ thay đổi", "Rất bền vững, ít chịu ảnh hưởng tình huống", "Không thể giáo dục", "Không liên quan hoạt động"], 0),
    ("Trong giao tiếp với trẻ, người lớn nên:",
     ["Quát mắng để trẻ nghe lời", "Sử dụng ngôn ngữ gần gũi, ánh mắt, cử chỉ thân thiện", "Ít nói chuyện", "Dùng lời đe dọa"], 1),
    ("Sự phát triển ngôn ngữ của trẻ gắn với:",
     ["Nhu cầu giao tiếp và hoạt động", "Tuổi sinh học thuần túy", "Chỉ số IQ", "Không liên quan môi trường"], 0),
    ("Một nhiệm vụ của giáo viên mầm non là phát hiện sớm:",
     ["Ý định di cư", "Thu nhập gia đình", "Nghề nghiệp tương lai", "Năng khiếu âm nhạc, hội họa, vận động"], 3),
    ("Trong quan hệ giáo viên - phụ huynh, ứng xử tâm lí phù hợp là:",
     ["Đổ lỗi cho gia đình", "Chỉ thông báo khi có vấn đề xấu", "Hợp tác, tôn trọng, chia sẻ thông tin hai chiều", "Giữ bí mật mọi chuyện của trẻ"], 2),
    ("Khi trẻ có hành vi lệch chuẩn, trước hết giáo viên cần:",
     ["Phạt thật nặng", "Phớt lờ", "Báo ngay cho nhà trường", "Bình tĩnh tìm hiểu nguyên nhân, hoàn cảnh"], 3),
    ("Việc hiểu rõ các giai đoạn phát triển tâm lí giúp giáo viên:",
     ["Đòi hỏi trẻ vượt quá khả năng", "Lựa chọn yêu cầu phù hợp, tạo “vùng phát triển gần nhất”", "Không cần điều chỉnh chương trình", "Giảm thời gian chơi"], 1),
    ("Ý nghĩa của nghiên cứu lịch sử tâm lí học với sinh viên:",
     ["Làm giàu vốn văn hoá nghề nghiệp", "Chỉ để ghi nhớ tên người", "Không liên quan sư phạm", "Chỉ cần đọc lướt"], 0),
    ("Nhà tâm lí học E. Erikson (tâm lí - xã hội) nhấn mạnh:",
     ["Hành vi bên ngoài", "Bản năng tình dục là trung tâm", "Các giai đoạn khủng hoảng tâm lí - xã hội gắn với nhiệm vụ phát triển", "Tính chỉnh thể của tri giác"], 2),
    ("Tâm lí học trẻ em hỗ trợ sinh viên mầm non ở chỗ:",
     ["Cung cấp kĩ năng y khoa", "Làm cơ sở khoa học cho nghệ thuật giáo dục trẻ", "Thay thế toàn bộ kinh nghiệm thực tế", "Không cần thiết nếu đã yêu trẻ"], 1),
    ("Để quan sát khách quan, giáo viên nên:",
     ["Ghi nhận cả hành vi tích cực và tiêu cực", "Chỉ ghi điều xấu", "Tin vào ấn tượng đầu tiên", "Không cần ghi chép"], 0),
    ("Trong phân tích số liệu nghiên cứu trẻ, việc dùng thống kê nhằm:",
     ["Trang trí báo cáo", "Không cần thiết", "Khái quát hoá, phát hiện quy luật", "Làm rối mắt người đọc"], 2),
    ("Hành vi “bắt chước người lớn” của trẻ mầm non cho thấy:",
     ["Trẻ thiếu chủ động", "Cần ngăn cấm", "Không có ý nghĩa", "Trẻ tiếp thu mẫu hành vi xã hội qua quan sát"], 3),
    ("Khi sử dụng thưởng, phạt, giáo viên cần:",
     ["Tuỳ hứng", "Thưởng thật nhiều, phạt thật nặng", "Nhất quán, công bằng, gắn với hành vi cụ thể", "Thưởng phạt theo cảm xúc cá nhân"], 2),
    ("Việc thiết kế môi trường góc chơi phong phú nhằm:",
     ["Đẹp lớp", "Kích thích hoạt động, phát triển nhận thức, tình cảm - xã hội", "Giảm công việc của giáo viên", "Thay thế giao tiếp"], 1),

    # ========== PART 3 (Q1-50) ==========
    ("Việc ghi nhật kí phát triển cho từng trẻ giúp:",
     ["Tăng giấy tờ", "Không có tác dụng", "Theo dõi tiến trình tâm lí cá nhân, điều chỉnh giáo dục", "Chỉ để báo cáo"], 2),
    ("Trong đánh giá trẻ, hình thức “quan sát liên tục trong ngày” thuộc:",
     ["Điều tra", "Thực nghiệm", "Trắc nghiệm", "Quan sát tự nhiên"], 3),
    ("Ví dụ của câu hỏi mở khi phỏng vấn trẻ:",
     ["“Con có thích chơi không? Có/Không”", "“Con hãy kể trò chơi con thích nhất”", "“Con có 5 tuổi không?”", "“Con đi học lúc mấy giờ?”"], 1),
    ("Đối với trẻ 5 tuổi, yêu cầu bài tập quá khó sẽ dẫn đến:",
     ["Căng thẳng, mất hứng thú", "Phát triển tốt", "Không ảnh hưởng", "Trẻ trưởng thành sớm"], 0),
    ("Khái niệm “chuẩn mực xã hội” mà trẻ lĩnh hội thông qua giáo dục là:",
     ["Luật pháp", "Lịch học", "Số lượng đồ chơi", "Hệ thống quy tắc, giá trị quy định hành vi đúng - sai"], 3),
    ("Trong giai đoạn mẫu giáo, tưởng tượng của trẻ:",
     ["Chưa xuất hiện", "Không liên quan chơi", "Rất phát triển, gắn chặt với trò chơi", "Hoàn toàn giống người lớn"], 2),
    ("Sự chú ý ở trẻ mầm non chủ yếu là:",
     ["Chú ý không chủ định, dễ bị kích thích bởi cái mới, lạ", "Chú ý có chủ định bền vững", "Không có chú ý", "Y như người lớn"], 0),
    ("Để rèn chú ý có chủ định, giáo viên nên:",
     ["Cho trẻ ngồi im lâu", "Tổ chức hoạt động hấp dẫn, có mục đích rõ ràng, tăng dần yêu cầu", "Bắt trẻ lặp đi lặp lại một động tác nhàm chán", "Cắt giảm thời gian chơi"], 1),
    ("Ý thức của trẻ mầm non về bản thân hình thành chủ yếu qua:",
     ["Soi gương", "Gen", "Đánh giá của người lớn, so sánh với bạn bè trong hoạt động", "Chiều cao"], 2),
    ("Tình bạn ở trẻ mầm non:",
     ["Không tồn tại", "Chỉ dựa trên lợi ích vật chất", "Giống hệt người lớn", "Đã xuất hiện, còn mang tính cảm xúc trực tiếp, chưa ổn định"], 3),
    ("Đặc điểm nhận thức cảm tính của trẻ mầm non là:",
     ["Phát triển yếu", "Giữ vai trò quan trọng, là cơ sở cho tư duy", "Không cần rèn luyện", "Tách rời hoạt động"], 1),
    ("Khi lập kế hoạch giáo dục, hiểu đặc điểm tâm lí từng độ tuổi giúp:",
     ["Lựa chọn mục tiêu, nội dung, phương pháp phù hợp", "Giảm bớt nội dung", "Không cần thiết", "Chỉ dùng để viết báo cáo"], 0),
    ("Trong lịch sử, các nhà giáo dục tiến bộ đã đấu tranh chống lại quan điểm:",
     ["Coi trẻ em như đối tượng giáo dục riêng", "Coi trẻ là người lớn thu nhỏ", "Tôn trọng trẻ", "Xem trọng giáo dục sớm"], 1),
    ("Các thuyết hiện đại đều thống nhất rằng phát triển tâm lí trẻ:",
     ["Do một yếu tố duy nhất quyết định", "Hoàn toàn ngẫu nhiên", "Là kết quả tương tác giữa di truyền, môi trường, giáo dục, hoạt động chủ thể", "Không thể tác động"], 2),
    ("Trong nghiên cứu tâm lí học trẻ em, đạo đức nghề nghiệp yêu cầu:",
     ["Có thể tiết lộ thông tin riêng tư của trẻ", "Tôn trọng, bảo mật, không làm tổn thương trẻ", "Dùng mọi biện pháp để có kết quả", "Ép trẻ tham gia nghiên cứu"], 1),
    ("Câu nói “mỗi đứa trẻ là một thế giới riêng” nhấn mạnh:",
     ["Tính cá biệt", "Tính di truyền", "Tính ngẫu nhiên", "Tính bất biến"], 0),
    ("Khi lựa chọn đề tài nghiên cứu nhỏ về trẻ mầm non, sinh viên nên:",
     ["Chọn vấn đề quá rộng", "Bỏ qua ý kiến giáo viên hướng dẫn", "Sao chép của người khác", "Chọn vấn đề cụ thể, gắn với thực tiễn lớp học"], 3),
    ("Phương pháp kết hợp “quan sát - phỏng vấn - phân tích sản phẩm” giúp:",
     ["Phục vụ thi cử", "Không cần thiết", "Rối rắm số liệu", "Tăng độ tin cậy và phong phú của kết luận"], 3),
    ("Một trong những đóng góp của tâm lí học trẻ em là:",
     ["Chứng minh giáo dục không thể thay đổi trẻ", "Khẳng định chỉ di truyền quyết định", "Đưa ra cơ sở khoa học cho việc cá thể hóa giáo dục", "Khuyến khích phạt nặng"], 2),
    ("Khi hiểu ngưỡng phát triển bình thường, giáo viên có thể:",
     ["Phát hiện sớm nguy cơ chậm phát triển để phối hợp can thiệp", "Bỏ qua trẻ chậm", "Không cần trao đổi với phụ huynh", "Đợi trẻ tự lớn"], 0),
    ("Quan điểm “chơi là hoạt động chủ đạo” dẫn tới yêu cầu:",
     ["Giảm tối đa thời gian chơi", "Chỉ cho chơi tự phát", "Tổ chức chơi có mục đích, nội dung giáo dục", "Thay chơi bằng học chữ hoàn toàn"], 2),
    ("Tâm lí học trẻ em coi giáo dục mầm non là:",
     ["Không cần thiết", "Hoạt động kinh doanh", "Chỉ là nơi trông trẻ", "Mắt xích đầu tiên, có ý nghĩa nền tảng cho sự phát triển sau này"], 3),
    ("Nhận xét đúng về trí nhớ trẻ mầm non:",
     ["Chỉ có trí nhớ máy móc", "Trí nhớ trực quan hình tượng phát triển mạnh; trí nhớ có chủ định bắt đầu hình thành", "Không thể rèn luyện", "Không nhớ được gì"], 1),
    ("Khả năng tư duy của trẻ mầm non chủ yếu ở dạng:",
     ["Tư duy trực quan - hành động và trực quan - hình tượng", "Tư duy trừu tượng thuần túy", "Chưa có tư duy", "Giống hệt người lớn"], 0),
    ("Đặc điểm tưởng tượng ở trẻ mầm non:",
     ["Không phong phú", "Hoàn toàn giống người lớn", "Gắn với trò chơi, giàu màu sắc nhưng còn ít kiểm soát", "Không có ý nghĩa giáo dục"], 2),
    ("Việc kể chuyện cổ tích giúp:",
     ["Phát triển tưởng tượng, ngôn ngữ, tình cảm đạo đức", "Giải trí đơn thuần", "Làm trẻ xa rời thực tế", "Không ảnh hưởng gì"], 0),
    ("Ở lứa tuổi mầm non, yếu tố ảnh hưởng mạnh tới hình thành thói quen hành vi là:",
     ["Di truyền", "Nêu gương, luyện tập trong hoạt động hằng ngày", "Truyền hình", "Chiều cao"], 1),
    ("Để tạo cảm giác an toàn tâm lí cho trẻ mới đến trường, giáo viên nên:",
     ["Buộc trẻ tách mẹ ngay", "Dọa nạt", "Không quan tâm cảm xúc trẻ", "Chào đón, làm quen dần, kết hợp phụ huynh"], 3),
    ("Nhận xét nào sai về vai trò gia đình với phát triển tâm lí trẻ:",
     ["Là môi trường giáo dục đầu tiên", "Ảnh hưởng lâu dài tới nhân cách", "Không quan trọng nếu trẻ đi học mầm non", "Góp phần hình thành thói quen, chuẩn mực"], 2),
    ("Khi xử lí xung đột giữa hai trẻ, giáo viên nên:",
     ["Quy kết một phía", "Hướng dẫn trẻ nói ra cảm xúc, tìm cách giải quyết hoà bình", "Phớt lờ", "Mắng cả hai trước lớp"], 1),
    ("Hiểu biết về xúc cảm - tình cảm giúp giáo viên:",
     ["Biết hỗ trợ điều chỉnh cảm xúc, xây dựng bầu khí tích cực", "Dễ phán xét trẻ", "Không cần thiết", "Chỉ dùng để an ủi phụ huynh"], 0),
    ("Trong quan sát, việc xác định “tình huống tiêu biểu” nhằm:",
     ["Tiết kiệm thời gian", "Giảm độ chính xác", "Nắm bắt rõ nét hành vi cần nghiên cứu", "Thay thế mọi dữ liệu khác"], 2),
    ("Hiện tượng “nhạy cảm thời điểm vàng” có nghĩa:",
     ["Trẻ dễ bệnh", "Không liên quan giáo dục", "Tất cả chức năng phát triển đồng đều", "Có những giai đoạn thuận lợi đặc biệt để hình thành một chức năng nào đó"], 3),
    ("Nguyên tắc khi đánh giá trẻ mầm non:",
     ["Dựa trên nhiều nguồn thông tin, quá trình, không so sánh trẻ này với trẻ khác một cách máy móc", "Chỉ dựa vào bài kiểm tra", "Chỉ nghe phụ huynh", "Chỉ chú ý lỗi sai"], 0),
    ("Khi sinh viên thực hiện nghiên cứu nhỏ ở trường mầm non, cần:",
     ["Tự ý khảo sát mà không xin phép", "Ghi âm, quay phim mọi lúc", "Thông qua ban giám hiệu, giáo viên, phụ huynh, tôn trọng luật lệ nhà trường", "Chỉ hỏi trẻ"], 2),
    ("Sự phát triển đạo đức ở trẻ mầm non biểu hiện qua:",
     ["Thu nhập gia đình", "Chỉ số IQ", "Sức khoẻ thể chất", "Thái độ, hành vi với người khác, khả năng làm theo quy tắc"], 3),
    ("Chơi phân vai theo chủ đề giúp trẻ:",
     ["Học thuộc lòng chữ số", "Lĩnh hội vai trò xã hội, phát triển ngôn ngữ và tình cảm", "Chỉ vận động", "Thư giãn không mục đích"], 1),
    ("Trong trò chơi có luật, trẻ rèn luyện:",
     ["Khả năng tuân thủ quy tắc, kiềm chế hành vi", "Tự do tuyệt đối", "Không rèn được gì", "Chỉ tốc độ chạy"], 0),
    ("Hiểu biết về quy luật “tích lũy dần dần rồi nhảy vọt” giúp giáo viên:",
     ["Nản chí khi chưa thấy kết quả", "Ngừng tác động", "Kiên trì giáo dục, biết chờ “bước nhảy” phát triển", "Tăng hình phạt"], 2),
    ("Ý nghĩa của việc học môn tâm lí học trẻ em đối:",
     ["Không cần thiết", "Không áp dụng được", "Chỉ để thi", "Giúp hiểu tâm lí trẻ, giao tiếp hiệu quả"], 3),
    ("Câu nói “Không có trẻ hư, chỉ có giáo dục chưa đúng cách” thể hiện niềm tin:",
     ["Giáo dục có khả năng cải biến nhân cách", "Di truyền quyết định tất cả", "Không thể thay đổi trẻ", "Trẻ luôn chống đối"], 0),
    ("Khả năng tự đánh giá của trẻ mầm non:",
     ["Chưa có", "Rất chính xác", "Bước đầu hình thành, còn phụ thuộc nhiều vào người lớn", "Không thay đổi"], 2),
    ("Đặc điểm tư duy của trẻ mầm non dễ dẫn đến:",
     ["Tư duy logic chặt chẽ", "Suy nghĩ theo cảm tính, phiến diện, chịu ảnh hưởng trực quan", "Không có sai lầm", "Hoàn toàn trừu tượng"], 1),
    ("Khi trẻ hỏi nhiều câu “Vì sao?”, điều đó cho thấy:",
     ["Trẻ nghịch", "Trẻ không bình thường", "Cần bị ngăn lại", "Nhu cầu nhận thức, tư duy đang phát triển"], 3),
    ("Phản ứng gắn bó với người chăm sóc chính ở trẻ nhỏ là:",
     ["Biểu hiện rối loạn", "Cần xoá bỏ", "Nhu cầu tự nhiên về an toàn, tình cảm", "Không quan trọng"], 2),
    ("Khi trẻ có dấu hiệu sợ trường, cô giáo nên:",
     ["Bỏ mặc", "Tìm hiểu nguyên nhân, phối hợp gia đình giúp trẻ thích nghi dần", "Ép buộc đến lớp", "Kỉ luật nặng"], 1),
    ("Công cụ đánh giá “phiếu nhận xét cuối ngày” của giáo viên nhằm:",
     ["Ghi lại biểu hiện nổi bật về hoạt động, hành vi, cảm xúc của trẻ", "Tăng giấy tờ", "Không cần thiết", "Chỉ để báo cáo hình thức"], 0),
    ("Sự khác nhau giữa quan sát tự nhiên và thực nghiệm là:",
     ["Đều không có mục đích", "Quan sát không can thiệp, thực nghiệm có can thiệp có chủ đích", "Thực nghiệm không ghi chép", "Quan sát diễn ra trong phòng thí nghiệm"], 1),
    ("Biểu hiện “tự kỉ trung tâm” ở trẻ mầm non có nghĩa:",
     ["Trẻ mắc bệnh tự kỉ", "Trẻ ích kỉ cố ý", "Trẻ có xu hướng xem mình là trung tâm, khó nhìn từ góc độ người khác", "Trẻ không biết nói"], 2),
    ("Hiểu hiện tượng “tự kỉ trung tâm” giúp giáo viên:",
     ["Kết luận trẻ hư", "Tăng phạt", "Phì cười bỏ qua", "Biết điều chỉnh yêu cầu, giúp trẻ dần biết quan tâm người khác"], 3),

    # ========== PART 4 (Q1-50) ==========
    ("Sự phát triển ngôn ngữ mạch lạc ở trẻ gắn liền với:",
     ["Học thuộc bài thơ dài", "Vẽ tranh", "Viết chữ", "Kể lại sự việc, câu chuyện theo trình tự"], 3),
    ("Để phát triển ngôn ngữ cho trẻ, giáo viên nên:",
     ["Nói thay trẻ", "Giảm thời gian trò chuyện", "Tạo cơ hội trẻ được giao tiếp, đàm thoại, kể chuyện", "Chỉ cho trẻ nghe băng"], 2),
    ("Một biểu hiện của trí tưởng tượng sáng tạo là:",
     ["Nhắc lại y nguyên mẫu", "Sáng tạo thêm chi tiết mới trong trò chơi, bức tranh", "Không dám thay đổi", "Chỉ sao chép"], 1),
    ("Cảm giác thành công của trẻ khi hoàn thành nhiệm vụ giúp:",
     ["Hình thành động cơ tích cực, lòng tự tin", "Không ảnh hưởng", "Khiến trẻ kiêu ngạo", "Làm trẻ lười"], 0),
    ("Khi trẻ thường xuyên bị phê bình trước lớp, hậu quả dễ thấy là:",
     ["Tăng ý thức", "Càng hăng hái", "Không bị ảnh hưởng", "Tự ti, tránh né hoạt động"], 3),
    ("Trong hoạt động nhóm, giáo viên cần chú ý phân công vai để:",
     ["Trẻ giành việc", "Mỗi trẻ đều tham gia, học cách hợp tác", "Tiết kiệm thời gian", "Chỉ trẻ giỏi làm"], 1),
    ("Việc sử dụng hình ảnh, đồ vật trực quan trong giờ học giúp:",
     ["Phù hợp đặc điểm tư duy trực quan, tăng hứng thú", "Làm đẹp lớp", "Gây xao nhãng", "Tốn kém vô ích"], 0),
    ("Thái độ ân cần, tôn trọng của giáo viên là điều kiện:",
     ["Không quan trọng", "Chỉ để phụ huynh hài lòng", "Tạo cảm giác an toàn, tin cậy, thuận lợi cho phát triển tâm lí", "Thay thế chuyên môn"], 2),
    ("Khi trẻ có hành vi tích cực, giáo viên nên:",
     ["Bỏ qua vì đó là bình thường", "Chỉ ghi nhận khi có phụ huynh", "Kịp thời ghi nhận, khích lệ", "So sánh với trẻ khác"], 2),
    ("Yếu tố giúp trẻ mầm non hình thành ý thức kỷ luật:",
     ["Phạt nặng", "Đe dọa", "Bắt thuộc lòng nội quy", "Nêu gương, quy định rõ ràng, giải thích, luyện tập qua hoạt động"], 3),
    ("Hiểu biết về cơ sở thần kinh của các quá trình tâm lí giúp:",
     ["Lý giải giới hạn sinh lí, chăm sóc sức khỏe tinh thần", "Thay thế vai trò giáo dục", "Không liên quan mầm non", "Chỉ cần trong y khoa"], 0),
    ("Khi trẻ mệt mỏi, cô vẫn đòi hỏi tập trung lâu dẫn đến:",
     ["Phát triển tốt hơn", "Không sao", "Quá tải, phản tác dụng", "Trẻ càng ngoan"], 2),
    ("Một biểu hiện của sự chín muồi về tâm lí để vào lớp 1 là:",
     ["Cao lớn", "Có mức chú ý, ghi nhớ, tư duy và ý thức kỉ luật phù hợp", "Biết đọc - viết trôi chảy", "Biết làm việc nhà"], 1),
    ("Hiểu về “chín muồi học đường” giúp giáo viên mầm non:",
     ["Dạy chữ quá sớm", "Quyết định trẻ lên lớp hay ở lại", "Không quan tâm", "Chuẩn bị các mặt phát triển cần thiết chứ không chỉ kĩ năng học thuật"], 3),
    ("Khi phân tích hành vi của trẻ, chú ý đến động cơ giúp:",
     ["Bỏ qua hậu quả", "Hiểu vì sao trẻ làm như vậy, từ đó giáo dục phù hợp", "Chỉ đánh giá kết quả", "Tăng hình phạt"], 1),
    ("Qua trò chơi, giáo viên có thể đánh giá:",
     ["Nhiều mặt như giao tiếp, tưởng tượng, tuân thủ luật, vai chơi", "Chỉ khả năng vận động", "Không đánh giá được gì", "Chỉ tính cách"], 0),
    ("Khi trẻ tỏ ra thụ động, ít chơi với bạn, giáo viên nên:",
     ["Bỏ mặc", "Gán nhãn “nhút nhát”", "Tạo tình huống, nhóm nhỏ khuyến khích trẻ tham gia dần", "Ép đứng trước lớp"], 2),
    ("Việc sử dụng kí hiệu đánh giá thay vì điểm số ở mầm non nhằm:",
     ["Cho đẹp", "Tránh gây áp lực, phù hợp đặc điểm tâm lí", "Không có lí do", "Dễ ghi chép"], 1),
    ("Hiểu về sự phát triển cảm giác, tri giác giúp giáo viên:",
     ["Thiết kế hoạt động giác quan phong phú", "Không cần thiết", "Chỉ chú ý nghe - nhìn", "Loại bỏ kích thích"], 0),
    ("Khi xây dựng đề tài nghiên cứu về trẻ, nội dung nên:",
     ["Trừu tượng", "Quá rộng", "Sao chép", "Gắn với thực tiễn chăm sóc - giáo dục, có giá trị ứng dụng"], 3),
    ("Tâm lí học trẻ em góp phần hình thành phẩm chất nghề nghiệp nào quan trọng cho giáo viên mầm non:",
     ["Tính vô cảm", "Tình yêu thương, tôn trọng trẻ trên cơ sở hiểu biết khoa học", "Thói quen áp đặt", "Tính nóng nảy"], 1),
    ("Việc hiểu “giá trị chuẩn mực xã hội” giúp giáo viên:",
     ["Áp đặt ý kiến cá nhân", "Chỉ dạy theo ý phụ huynh", "Giáo dục trẻ biết điều hay, lẽ phải theo chuẩn chung", "Không cần thiết"], 2),
    ("Khi trẻ hỏi những vấn đề nhạy cảm, giáo viên nên:",
     ["Giải thích đơn giản, phù hợp lứa tuổi, tránh dối trá", "Gạt đi", "Mắng", "Đổ cho phụ huynh"], 0),
    ("Để phát hiện năng lực đặc biệt, giáo viên cần:",
     ["Chỉ nhìn điểm số", "Đợi đến tiểu học", "Chỉ nghe phụ huynh", "Quan sát lâu dài trong nhiều hoạt động"], 3),
    ("Khi tổ chức hoạt động khám phá khoa học, giáo viên vận dụng:",
     ["Quan điểm hành vi", "Nguyên tắc “học bằng hoạt động, trải nghiệm”", "Chỉ đọc bài", "Cho xem phim"], 1),
    ("Kiến thức về tâm lí học trẻ em giúp giáo viên:",
     ["Chỉ giải quyết mâu thuẫn với phụ huynh", "Không có giá trị", "Chủ động phòng ngừa khó khăn tâm lí cho trẻ", "Chỉ dùng khi dạy môn “Làm quen với toán”"], 2),
    ("Trong nghiên cứu, việc kiểm soát biến nhiễu là để:",
     ["Tăng độ chính xác của kết luận", "Đơn giản hóa thí nghiệm", "Làm phức tạp", "Không quan trọng"], 0),
    ("Tình huống “trẻ khóc khi mẹ đi” là phản ứng:",
     ["Bất thường", "Bỏ qua", "Cần phạt", "Bình thường trong giai đoạn gắn bó, cần hỗ trợ thích nghi"], 3),
    ("Khi trẻ có biểu hiện chậm nói, giáo viên nên:",
     ["Chờ sẽ tự hết", "Trao đổi với phụ huynh, khuyến nghị khám chuyên môn khi cần", "Mắng trẻ", "Không nói với ai"], 1),
    ("Hiểu biết về phát triển bình thường và lệch chuẩn giúp:",
     ["Kết luận trẻ hư", "Không tác động", "Phát hiện sớm, can thiệp kịp thời", "Tăng hình phạt"], 2),
    ("Trong lịch sử, sự xuất hiện của các viện nghiên cứu, phòng thí nghiệm tâm lí trẻ em cho thấy:",
     ["Môn học không quan trọng", "Tâm lí học trẻ em trở thành ngành khoa học thực nghiệm", "Chỉ mang tính lí thuyết", "Không được quan tâm"], 1),
    ("Ở lứa tuổi mầm non, tính bắt chước giúp:",
     ["Trẻ học các hành vi xã hội", "Trẻ mất tự chủ", "Không có ích", "Nên ngăn cấm"], 0),
    ("Khi giáo viên tự đánh giá giờ dạy của mình, đó là biểu hiện:",
     ["Thiếu tự tin", "Không cần thiết", "Lãng phí", "Năng lực phản tư, tự hoàn thiện"], 3),
    ("Để xây dựng mối quan hệ tích cực với trẻ, giáo viên cần:",
     ["Kết hợp yêu thương, tôn trọng, nhất quán trong yêu cầu", "Chỉ dùng mệnh lệnh", "Nuông chiều", "Bỏ qua nội quy"], 0),
    ("Khi trẻ kể chuyện “không đúng sự thật”, giáo viên nên:",
     ["Kết luận trẻ nói dối", "Bỏ qua", "Phạt nặng", "Phân biệt giữa tưởng tượng và cố ý lừa dối, hướng dẫn nói thật trong tình huống cần thiết"], 3),
    ("Việc tổ chức hoạt động nhóm nhỏ thường xuyên giúp:",
     ["Lớp ồn hơn", "Không có tác dụng", "Phát triển kĩ năng hợp tác, giao tiếp", "Tăng mâu thuẫn"], 2),
    ("Tâm lí học trẻ em khẳng định:",
     ["Chỉ người mẹ mới giáo dục được trẻ", "Mọi người lớn đều ảnh hưởng tới trẻ, đặc biệt là người gần gũi", "Chỉ giáo viên", "Chỉ bạn bè"], 1),
    ("Hiểu về “xu hướng bắt chước thần tượng” giúp giáo viên:",
     ["Ngăn cấm mọi hình mẫu", "Không quan tâm", "Chọn lọc, giới thiệu gương tốt cho trẻ noi theo", "Chỉ để phụ huynh quyết định"], 2),
    ("Một trong những đặc điểm của tư duy trực quan - hình tượng là:",
     ["Dựa trên hình ảnh cụ thể, sinh động", "Dựa trên thao tác logic kí hiệu", "Không dựa trên gì", "Hoàn toàn trừu tượng"], 0),
    ("Khi dạy trẻ khái niệm trừu tượng, giáo viên nên:",
     ["Giải thích bằng lời dài", "Sử dụng đồ vật, tranh ảnh, tình huống cụ thể trước", "Bỏ qua", "Cho trẻ tự tìm hiểu"], 1),
    ("Tình cảm gắn bó với cô giáo được hình thành qua:",
     ["Phạt nặng", "Dọa nạt", "Đưa quà", "Quan tâm, chăm sóc, nhất quán, công bằng"], 3),
    ("Việc luân phiên vai trò trong trò chơi giúp:",
     ["Mỗi trẻ trải nghiệm nhiều vị trí xã hội khác nhau", "Trẻ giành quyền", "Không có ý nghĩa", "Chỉ tốn thời gian"], 0),
    ("Hiểu biết về “tự ý thức” giúp giáo viên:",
     ["Làm trẻ xấu hổ", "Hỗ trợ trẻ biết nhận xét bản thân tích cực, thực tế", "Không cần thiết", "Bỏ qua cảm xúc"], 1),
    ("Khi xây dựng nội quy lớp, giáo viên nên:",
     ["Thảo luận cùng trẻ, dùng lời lẽ ngắn gọn, dễ hiểu", "Tự đặt", "Viết thật dài", "Chỉ thông báo phụ huynh"], 0),
    ("Việc cho trẻ tham gia đánh giá hoạt động cuối ngày giúp:",
     ["Tốn thời gian", "Làm trẻ mệt", "Không ích lợi", "Rèn kĩ năng tự đánh giá, bộc lộ cảm xúc"], 3),
    ("Một trong những nội dung quan trọng của giáo dục mầm non là:",
     ["Dạy kiến thức hàn lâm", "Chỉ dạy chữ", "Phát triển toàn diện thể chất, nhận thức, ngôn ngữ, tình cảm - xã hội, thẩm mĩ", "Chỉ trông trẻ"], 2),
    ("Nghiên cứu tâm lí trẻ em giúp xã hội:",
     ["Không thay đổi gì", "Xây dựng chính sách, chương trình phù hợp với trẻ em", "Giảm chi phí giáo dục", "Tăng áp lực"], 1),
    ("Quan điểm “tôn trọng sự khác biệt cá nhân” trong giáo dục mầm non nghĩa là:",
     ["Ghi nhận đặc điểm riêng, hỗ trợ phù hợp, không kì thị", "Đối xử khác biệt về quyền lợi", "Không cần nội quy chung", "Muốn làm gì cũng được"], 0),
    ("Khi trẻ thể hiện cảm xúc mạnh (khóc, giận), giáo viên nên:",
     ["Bảo “con lớn rồi, đừng khóc”", "Thừa nhận cảm xúc, giúp trẻ gọi tên và bình tĩnh lại", "Phớt lờ", "Chê bai"], 1),
    ("Kết luận quan trọng rút ra từ tâm lí học trẻ em đối với người làm nghề mầm non là:",
     ["Giáo dục không ảnh hưởng", "Chỉ cần chương trình học", "Chỉ cần kinh nghiệm", "Cần kết hợp hiểu biết khoa học với tình yêu nghề, yêu trẻ để nuôi dưỡng và giáo dục hiệu quả"], 3),
]

assert len(QUESTIONS) == 200, f"Expected 200 questions, got {len(QUESTIONS)}"

# Build JSON-serializable list
data = [
    {"q": q, "options": opts, "answer": ans}
    for q, opts, ans in QUESTIONS
]

with open("questions.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=1)

print(f"Saved {len(data)} questions to questions.json")
